### ISSUE TITLE
HFValidationError

### ISSUE THREAD

**Issue by Alijin** [yao8839836/kg-llm#1]
Hi, thank you for your excellent work. When I run the 'python lora_finetune_wn11.py' , there is an error as following,

Traceback (most recent call last):
  File "E:/kg-llm-main/lora_finetune_wn11.py", line 45, in <module>
    model = LlamaForCausalLM.from_pretrained(
  File "D:\learn_install\Anaconda32020\envs\KGCLLM\lib\site-packages\transformers\modeling_utils.py", line 2377, in from_pretrained
    resolved_config_file = cached_file(
  File "D:\learn_install\Anaconda32020\envs\KGCLLM\lib\site-packages\transformers\utils\hub.py", line 429, in cached_file
    resolved_file = hf_hub_download(
  File "D:\learn_install\Anaconda32020\envs\KGCLLM\lib\site-packages\huggingface_hub\utils\_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "D:\learn_install\Anaconda32020\envs\KGCLLM\lib\site-packages\huggingface_hub\utils\_validators.py", line 158, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'models/LLaMA-HF/llama-13b'. Use `repo_type` argument if needed.
Process finished with exit code 1

Could you please provide some  guidance? Hoping for your reply.Thanks again.

**Comment by yao8839836** [comment]
@Alijin  Hi, thank you for your interest in our work.

Have you put the llama-13b model files under your models/LLaMA-HF/llama-13b/ ? like this:

![image](https://github.com/yao8839836/kg-llm/assets/7744044/c1e03e84-a51b-4fe4-a83e-eeade93e6e85)

The files under models/LLaMA-HF/tokenizer/ are:

![企业微信截图_16938177835892](https://github.com/yao8839836/kg-llm/assets/7744044/ca70b396-874d-41e3-833d-5ab6c28865e6)

**Comment by Alijin** [comment]
Thank you so much for your help. I will put the model in the correct path and try again.
